# Artificial Neural Network

### Importing the libraries

In [1]:
#pip install tensorflow

import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
# Import the os module
import os
# Get the current working directory
cwd = os.getcwd()
print(cwd)

# Change the current working directory
os.chdir('C:/Users/javij/OneDrive/Documentos/GitHub/Material-CNBV/MOD 8/Datasets')

actual = os.getcwd()
print(actual)

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

FileNotFoundError: [Errno 2] File Churn_Modelling.csv does not exist: 'Churn_Modelling.csv'

In [6]:

X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [21]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


### Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [25]:
print(X)

[[ 0.57873591 -0.57873591  0.99720391 ...  0.64609167  0.97024255
   0.02188649]
 [ 0.57873591 -0.57873591 -1.00280393 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.57873591 -0.57873591  0.99720391 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.57873591 -0.57873591  0.99720391 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.72790383  1.72790383 -1.00280393 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.57873591 -0.57873591  0.99720391 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [27]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [29]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [30]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [31]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [32]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7824
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4632 - accuracy: 0.8020
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.8061
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.8096
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4267 - accuracy: 0.8141
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4213 - accuracy: 0.8174
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4166 - accuracy: 0.8185
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4123 - accuracy: 0.8205
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4081 - accuracy: 0.8213
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4037 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8622
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3340 - accuracy: 0.8601
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3338 - accuracy: 0.8626
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8619
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3334 - accuracy: 0.8630
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3334 - accuracy: 0.8600
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3334 - accuracy: 0.8594
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3334 - accuracy: 0.8629
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3334 - accuracy: 0.8621
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [0]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1515   80]
 [ 198  207]]
